bootstrap.servers=kafka:29092
group.id=streamlens-connect
config.storage.topic=_connect-configs
offset.storage.topic=_connect-offsets
status.storage.topic=_connect-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
rest.port=8083
rest.advertised.host.name=kafka-connect
plugin.path=/opt/kafka/libs
